const COMMENT_CREATED = "COMMENT_CREATED"
const COMMENT_MODERATED = "COMMENT_MODERATED"
const COMMENT_REJECTED = "COMMENT_REJECTED"

export {
    COMMENT_CREATED,
    COMMENT_MODERATED,
    COMMENT_REJECTED
}