const MEMORY_DB = "MEMORY_DB"
const POST_CREATED = "POST_CREATED"
const COMMENT_CREATED = "COMMENT_CREATED"
const COMMENT_UPDATED = "COMMENT_UPDATED"

export {
    MEMORY_DB,
    POST_CREATED,
    COMMENT_CREATED,
    COMMENT_UPDATED
}