const MEMORY_DB = "MEMORY_DB"
const COMMENT_CREATED = "COMMENT_CREATED"
const COMMENT_MODERATED = "COMMENT_MODERATED"
const COMMENT_REJECTED = "COMMENT_REJECTED"
const COMMENT_UPDATED = "COMMENT_UPDATED"
const SEND_COMMENT_UPDATE = "SEND_COMMENT_UPDATE"

export {
    MEMORY_DB,
    COMMENT_CREATED,
    COMMENT_MODERATED,
    COMMENT_REJECTED,
    COMMENT_UPDATED,
    SEND_COMMENT_UPDATE
}